### ISSUE TITLE
Link to CV is broken

### ISSUE THREAD

**Issue by SeuRonao** [snt85c/Portfolio#1]
Hello,
just a warning that the link to your CV is broken at the moment.

![image](https://user-images.githubusercontent.com/22750712/204587803-7f82a97b-70a6-4a73-b7fc-a0e58c62931f.png)

Here you can see that there is no reference to the button:

![image](https://user-images.githubusercontent.com/22750712/204588019-bb5558c8-0583-4012-a465-f413756c13f9.png)

Wish you well and good luck.

**Comment by snt85c** [comment]
Hi Ronan, thanks for this notification.

 Truth to be told I haven't finished editing my CV due to new work requests so I never intended the button to link to anything at this stage.

Still, I appreciate the heads-up!

Regards

Santi

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Ronan Soares ***@***.***>
Sent: Tuesday, November 29, 2022 4:36:27 PM
To: snt85c/Portfolio ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [snt85c/Portfolio] Link to CV is broken (Issue #1)


Hello,
just a warning that the link to your CV is broken at the moment.

[image]<https://user-images.githubusercontent.com/22750712/204587803-7f82a97b-70a6-4a73-b7fc-a0e58c62931f.png>

Here you can see that there is no reference to the button:

[image]<https://user-images.githubusercontent.com/22750712/204588019-bb5558c8-0583-4012-a465-f413756c13f9.png>

Wish you well and good luck.
